%perlcode %{
@EXPORT_OK = qw/
    gsl_rstat_quantile_alloc
    gsl_rstat_quantile_free
    gsl_rstat_quantile_reset
    gsl_rstat_quantile_add
    gsl_rstat_quantile_get
    gsl_rstat_alloc
    gsl_rstat_free
    gsl_rstat_n
    gsl_rstat_add
    gsl_rstat_min
    gsl_rstat_max
    gsl_rstat_mean
    gsl_rstat_variance
    gsl_rstat_sd
    gsl_rstat_rms
    gsl_rstat_sd_mean
    gsl_rstat_median
    gsl_rstat_skew
    gsl_rstat_kurtosis
    gsl_rstat_reset
/;

%EXPORT_TAGS = (
                all => \@EXPORT_OK,
               );
__END__

=encoding utf8

=head1 NAME

Math::GSL::Rstat - Running Statistical functions

=head1 SYNOPSIS

    use Math::GSL::Rstat qw /:all/;
    my @data = (17.2, 18.1, 16.5, 18.3, 12.6);
    map { gsl_rstat_add( $_, $rstat) } @data;
    my $rstat    = gsl_rstat_alloc();
    my $mean     = gsl_rstat_mean($rstat);
    my $variance = gsl_rstat_variance($rstat);
    my $largest  = gsl_rstat_max($rstat);
    my $smallest = gsl_rstat_min($rstat);
    my $sd       = gsl_rstat_sd($rstat);
    my $rms      = gsl_rstat_rms($rstat);
    my $sd_mean  = gsl_rstat_sd_mean($rstat);
    my $median   = gsl_rstat_median($rstat);
    my $skew     = gsl_rstat_skew($rstat);
    my $kurtosis = gsl_rstat_kurtosis($rstat);
    my $n        = gsl_rstat_n($rstat);

=head1 DESCRIPTION

NOTE: This module requires GSL 2.0 or higher.

For more informations on the functions, we refer you to the GSL offcial
documentation: L<http://www.gnu.org/software/gsl/manual/html_node/>

=head1 AUTHORS

Jonathan "Duke" Leto <jonathan@leto.net>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2008-2016 Jonathan "Duke" Leto

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut

%}
