#!/usr/bin/perl -w


use Config;
# Build.PL needs to do this
# this seems to not like perl 5.8, but is known to work on linux+freebsd for
# perl 5.10

my $archlib = $Config{archlib};
my $swig = "swig";
my $opt  = "-shadow -Wall -perl5"; 

my @swigs = qw/
    BLAS Block Bspline CBLAS CDF Chebyshev CheckRange Combination Complex
    Const Deriv DFT DHT Diff Eigen Errno FFT Fit Heapsort Histogram Histogram2d
    IEEEUtils Integration Interp Linalg Machine Math Matrix Message Min Mode Monte
    Multifit Multimin Multiroots NAN Ntuple ODEIV Permutation Permute Poly PowInt Precision
    QRNG Randist RNG Roots SF Siman Sort Specfunc Spline Statistics Sum Sys Test Types Vector
    Version Wavelet Wavelet2d
   /;

# to do all
#map { system "$swig $opt -module Math::GSL::$_ $_.i" } @swigs;

system "$swig $opt -module Math::GSL::SF SF.i";

my $cmd2= q{ gcc -Wall -fpic -c SF_wrap.c  -Dbool=char -I}.$archlib.q{/CORE -I/usr/local/include/};

my $cmd3= q{ gcc -L/usr/local/lib -shared SF_wrap.o -lgsl -o SF.so};

print "Running $cmd2 && $cmd3\n";
system "$cmd2 && $cmd3";

