#!/usr/bin/perl -w

use Test::More tests=> 2;
use Sf;

my $eps = 1e-8;

my %results = ( 
                'gsl_sf_gamma(6.3)' =>  201.813275184748,
                'gsl_sf_erf(5)'     => 0.999999999998463,
              );

while (my($k,$v)=each %results){
    my $x = eval "Math::GSL::Sf::$k";
    my $res = abs($x - $v);
    ok( $res < $eps, "$k ?= $x, res=$res" );    
}

