#!/usr/bin/perl -w
use Math::GSL::Statistics qw/gsl_stats_correlation/;
use strict;

my $data1 = [
            17, 18, 16, 18, 12,
            20, 18, 20, 20, 22,
            20, 10, 8, 12, 16,
            16, 18, 20, 18, 21
            ];

my $data2 = [
            19, 20, 22, 24, 10,
            25, 20, 22, 21, 23,
            20, 10, 12, 14, 12,
            20, 22, 24, 23, 17
            ];

my $x = gsl_stats_correlation($data1, 1, $data2, 1, 20);
print "x=$x\n";
